const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Keyboard.Acts.LockKeyboard
	];
};
self.C3_JsPropNameTable = [
	{Fundo: 0},
	{Mouse: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Jogador: 0},
	{health: 0},
	{Projétil: 0},
	{Zombie: 0},
	{DestruirForaDoLayout: 0},
	{Esmaecer: 0},
	{Flash: 0},
	{EntradaDeTexto: 0},
	{Texto: 0},
	{RankingDeJogadores: 0},
	{NomedOjogador: 0},
	{Botão: 0},
	{Teclado: 0},
	{AJAX: 0},
	{GameOverText: 0},
	{zombieSpeed: 0},
	{Pontos: 0},
	{Score: 0}
];

self.InstanceType = {
	Fundo: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Zombie: class extends self.ISpriteInstance {},
	Projétil: class extends self.ISpriteInstance {},
	Flash: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Texto: class extends self.ITextInstance {},
	RankingDeJogadores: class extends self.ITextInstance {},
	NomedOjogador: class extends self.ITextInputInstance {},
	Botão: class extends self.IButtonInstance {},
	Teclado: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	GameOverText: class extends self.ITextInstance {}
}